### ISSUE TITLE
Memory leak or at least excessive memory consumption

### ISSUE THREAD

**Issue by Ga0l** [scikit-hep/pyhf#934] opened 2020-07-09 12:24 UTC
# Description

I noticed a big memory hog when running a certain number of iterations of `pyhf.infer.hypotest`. This strange behaviour has been confirmed with a small code that repeatedly executes `hypotest`.
A similar behavior has been noticed when switching backends.

# Expected Behavior

Memory profile should be constant when using `pyhf.infer.hypotest` or switching backends.

# Actual Behavior

The following behavior was observed by using the python `memory_profile` library :
- When running `pyhf.infer.hypotest` 10000 times in a row, memory consumption is constantly growing.
- Similarly, when switching backends with `pyhf.set_backend()` repeatedly, an anomalous memory consumption can be observed.

# Steps to Reproduce

pyhf version 0.4.1 was used. In [attachment](https://github.com/scikit-hep/pyhf/files/4896635/attachment.zip), you can find the following files :

- `memPyhf.py` : a code that executes `pyhf.infer.hypotest` 10000 times in a row using a simple json definition
- `mprofile_hypotest.dat` : the memory profile of `memPyhf.py` (made with `mprof run memPyhf.py`)
- `switchBackends.py` : a code that switches backends a 1000 times in a row
- `mprofile_switchBackends.dat` : memory profile of `switchBackends.py`

The memory profiles can be reproduced by running `mprof run memPyhf.py` or `mprof run switchBackends.py` with the two python scripts.

# Checklist

- [ ] Run `git fetch` to get the most up to date version of `master`
- [x] Searched through existing Issues to confirm this is not a duplicate issue
- [x] Filled out the Description, Expected Behavior, Actual Behavior, and Steps to Reproduce sections above or have edited/removed them in a way that fully describes the issue

**Comment by kratsg** [comment] 2020-07-09 12:42
hi @Ga0l , for the 2nd part. I added a `time.sleep(1.0)` at the beginning of the for-loop to try and determine if switching backends is causing a memory increase -- it's not.

<img width="1372" alt="Screenshot 2020-07-09 08 05 28" src="https://user-images.githubusercontent.com/761483/87038011-214d9880-c1bb-11ea-82d4-2d0ed7547bf1.png">

This is just because tensorflow/jax are large backends and take up a bit of memory upon import. Not sure we can do anything about that.

**Comment by kratsg** [comment] 2020-07-09 13:38
For the first case, you're likely hitting this issue: pytorch/pytorch#1346 since we're using the auto-grad features and things are probably not freed as part of the loop.

**Comment by WolfgangWaltenberger** [comment] 2020-07-24 14:07
Hey. Is there any progress so far on this from your side? I am now also digging a bit into this, I played with garbace collecting, reloading of libraries, and mprof, but to no avail. Now I have started using pympler, and I see now that some python lists are growing endlessly. I retrieved their names via inspection, it seems they are called "l". But I didnt find any suspicious "l" variables in the pyhf code. Does that tell you guys anything?

**Comment by WolfgangWaltenberger** [comment] 2020-07-24 14:22
Ah sorry, I forgot about the autograd issue, @kratsg mentioned. If you use pympler

all_objects = muppy.get_objects()
sum1 = summary.summarize(all_objects)
summary.print_(sum1)

It seems that the (main) culprit is pure python, it is python lists. That speaks a bit against the autograd hypothesis, I guess.

**Comment by kratsg** [comment] 2020-07-24 18:03
so I ran `memPyhf.py` with a pympler summary before and after the main call

before
```
                       types |   # objects |   total size
============================ | =========== | ============
                         str |       53069 |     10.69 MB
                        dict |       14942 |      6.77 MB
                        type |        3149 |      2.70 MB
                        code |       16884 |      2.33 MB
                       tuple |       13778 |    893.85 KB
                         set |         861 |    571.84 KB
                        list |        2526 |    388.25 KB
                     weakref |        3786 |    295.78 KB
           getset_descriptor |        3710 |    260.86 KB
           method_descriptor |        3663 |    257.55 KB
          _io.BufferedWriter |           2 |    256.34 KB
  builtin_function_or_method |        3583 |    251.93 KB
          wrapper_descriptor |        3078 |    240.47 KB
                         int |        5381 |    162.51 KB
         function (__init__) |        1213 |    161.10 KB
```

after
```
                             types |   # objects |   total size
================================== | =========== | ============
                               str |       64377 |     11.50 MB
                              dict |       25026 |      8.23 MB
                              list |       62613 |      6.55 MB
                              type |        3162 |      2.71 MB
                              code |       16884 |      2.33 MB
                      torch.Tensor |       30075 |      2.07 MB
                             tuple |       13814 |    896.56 KB
                            method |       10933 |    683.31 KB
                       numpy.int64 |       20000 |    625.00 KB
                               set |         866 |    572.94 KB
  pyhf.tensor.common._TensorViewer |       10016 |    547.75 KB
                           weakref |        3845 |    300.39 KB
                 getset_descriptor |        3710 |    260.86 KB
                 method_descriptor |        3675 |    258.40 KB
                _io.BufferedWriter |           2 |    256.34 KB
```

so I can at least confirm it seems like lists are increasing the most. Digging into this more.

**Comment by kratsg** [comment] 2020-07-24 18:05
Using the memory tracker feature via

```python
    tr = tracker.SummaryTracker()
    main()
    tr.print_diff()
```

gives us

```
                             types |   # objects |   total size
================================== | =========== | ============
                              list |       60091 |      4.90 MB
                      torch.Tensor |       30075 |      2.07 MB
                              dict |       10072 |      1.46 MB
                               str |       10048 |    719.60 KB
                            method |       10036 |    627.25 KB
                       numpy.int64 |       20000 |    625.00 KB
  pyhf.tensor.common._TensorViewer |       10016 |    547.75 KB
             pyhf.events.Callables |           1 |     85.59 KB
                               int |        1905 |     52.09 KB
                     numpy.ndarray |          45 |      4.71 KB
                           weakref |          44 |      3.44 KB
        builtin_function_or_method |          38 |      2.67 KB
                              type |           0 |      2.55 KB
                             tuple |          33 |      2.51 KB
          urllib.parse.SplitResult |          19 |      1.63 KB
```

**Comment by WolfgangWaltenberger** [comment] 2020-07-24 18:20
I ran this on top of our interface to pyhf, so I cannot easily extract a standalone code snippet. But yes, lists grow the fastest. In addition I applied the code snippet below (stolen from stack exchange) on "all_objects". For the lists it says "l". If you look into these lists, you should find a gigantic number of pointers, no idea where they point to.

import inspect

def retrieve_name(var):                                                                        
    callers_local_vars = inspect.currentframe().f_back.f_locals.items()                       
    return [var_name for var_name, var_val in callers_local_vars if var_val is var]

**Comment by kratsg** [comment] 2020-07-24 18:21
How do you see the lists?

**Comment by WolfgangWaltenberger** [comment] 2020-07-24 18:49
> How do you see the lists?

all_objects = muppy.get_objects()

Then I filtered out the lists:

lists = [ao for ao in all_objects if isinstance(ao, list)]

Then I only looked at the ones that became enormously large:

for l in lists:                                                                           
        if len(l)>100000:                                                                     
            print ( "list of size %d, name=``%s''" % ( len(l), retrieve_name(l) ) )


I am a bit puzzled. It looks a bit like this is from some C library (as in python you wouldnt store addresses/pointers, would you)
but then again, its a python list. So I dont really understand what is going on here.

**Comment by kratsg** [comment] 2020-07-24 20:49
It seems like there's no observed leak when using v0.5.0 (master). This will be confirmed by @WolfgangWaltenberger later.

**Comment by matthewfeickert** [comment] 2020-07-24 20:52
@WolfgangWaltenberger We should have `v0.5.0` out on PyPI in the next 24 hours. We'll ping you when it is available.

**Comment by matthewfeickert** [comment] 2020-07-27 04:53
@WolfgangWaltenberger `v0.5.0` is out on PyPI and Conda-forge now.

**Comment by Ga0l** [comment] 2020-08-04 08:09
Hi all,

I've tested the code snippet that repeatedly executes `hypotest` with `v0.5.1` and there is no memory leak anymore.
However, we still have a memory leak in our `SModelS/pyhf` interface, but then the problem must lie somewhere in our interface.

Thanks for the help!

**Comment by matthewfeickert** [comment] 2020-08-04 08:16
> I've tested the code snippet that repeatedly executes `hypotest` with `v0.5.1` and there is no memory leak anymore.
> However, we still have a memory leak in our `SModelS/pyhf` interface, but then the problem must lie somewhere in our interface.

Glad to know that things have been narrowed down at least. Please let us know if we can do anything to help test things.

I'll go ahead and close this now as it seems things are resolved, but we're happy to reopen if there is need for further discussion.

**Closed by matthewfeickert** 2020-08-04 08:16 UTC
Labels: bug, question

**Comment by Ga0l** [comment] 2020-08-06 13:59
Hi all,

I just notice that if I change the code from this
```
llhdSpec = jsonpatch.apply_patch(bkg, patch)
msettings = {'normsys': {'interpcode': 'code4'}, 'histosys': {'interpcode': 'code4p'}}
workspace = pyhf.Workspace(llhdSpec)
model = workspace.model(modifier_settings=msettings)
for _ in range(10000):
    result = pyhf.infer.hypotest( 1., workspace.data(model), model, qtilde=True, return_expected=False)
```
to this
```
llhdSpec = jsonpatch.apply_patch(bkg, patch)
msettings = {'normsys': {'interpcode': 'code4'}, 'histosys': {'interpcode': 'code4p'}}
workspace = pyhf.Workspace(llhdSpec)
for _ in range(10000):
    model = workspace.model(modifier_settings=msettings)
    result = pyhf.infer.hypotest( 1., workspace.data(model), model, qtilde=True, return_expected=False)
```
then the memory leak comes back. [Here's](https://github.com/scikit-hep/pyhf/files/5035008/memPyhf.zip) the complete code snippet if needed. In `SModelS`, this `model` variable is redefined before each use of `hypotest` so that could be our problem.

**Comment by Ga0l** [comment] 2020-08-18 09:24
Hi all,

I just noticed that the `zip` file in my previous message was broken, sorry for that. I'm attaching it [here](https://github.com/scikit-hep/pyhf/files/5089327/memPyhf.zip) again.

**Comment by Ga0l** [comment] 2020-08-18 14:20
[Here's](https://github.com/scikit-hep/pyhf/files/5090893/memPyhf.zip) the code snippet without the `hypotest` line, which also leads to a memory hog (we do `mprof run memPyhf.py` to monitor memory consumption).

**Comment by lukasheinrich** [comment] 2020-08-18 14:25
we can reduce this further

```
#!/usr/bin/env python3

import sys
import pyhf
pyhf.set_backend(b"pytorch")
from memory_profiler import profile

@profile
def main():
    for _ in range(1000):
        model = pyhf.simplemodels.hepdata_like([1],[1],[1 ])


main()
```

gives

```
python -m memory_profiler memleak.py 
Filename: memleak.py

Line #    Mem usage    Increment   Line Contents
================================================
     8    126.6 MiB    126.6 MiB   @profile
     9                             def main():
    10    197.2 MiB      0.0 MiB       for _ in range(1000):
    11    197.2 MiB      1.3 MiB           model = pyhf.simplemodels.hepdata_like([1],[1],[1 ])

```

**Comment by lukasheinrich** [comment] 2020-08-18 14:26
```
python -m memory_profiler memleak.py 
Filename: memleak.py

Line #    Mem usage    Increment   Line Contents
================================================
     8     79.6 MiB     79.6 MiB   @profile
     9                             def main():
    10    120.3 MiB      0.0 MiB       for _ in range(1000):
    11    120.3 MiB      0.2 MiB           model = pyhf.simplemodels.hepdata_like([1],[1],[1 ])
```

when  commenting out `.set_backend("pytorch")` 

better but not zero

**Comment by lukasheinrich** [comment] 2020-08-18 14:40
```
import pyhf
pyhf.set_backend(b"pytorch")
from memory_profiler import profile

@profile
def main():
    for _ in range(1000):
        pyhf.tensorlib.astensor([1]*10000)
main()
```

gives

```
python -m memory_profiler memleak.py 
Filename: memleak.py

Line #    Mem usage    Increment   Line Contents
================================================
     8    127.0 MiB    127.0 MiB   @profile
     9                             def main():
    10    127.3 MiB      0.0 MiB       for _ in range(1000):
    11    127.3 MiB      0.3 MiB           pyhf.tensorlib.astensor([1]*10000)
```

(same for numpy just less memory..)

**Comment by lukasheinrich** [comment] 2020-08-18 14:57
```
#!/usr/bin/env python3

import sys
import pyhf
import numpy as np
import torch
from memory_profiler import profile
from pyhf.parameters import ParamViewer
import os

@profile
def main():
    print(os.getpid())
    N = 10000
    for _ in range(10000):
        view = ParamViewer((1000,),{'hello': {'slice': slice(0, 1)}},['hello'],)
        del view

main()
```

seem to be a more minimal case

**Comment by lukasheinrich** [comment] 2020-08-18 15:23
```
#!/usr/bin/env python3
import os
import pyhf
from pyhf import get_backend, events

class DummyObject(object):
    def __init__(self, indices):
        events.subscribe('tensorlib_changed')(self._precompute)
        pass

    def _precompute(self):
        tensorlib, _ = get_backend()
        pass

def main():
    print(os.getpid())
    N = 10000
    a = pyhf.tensorlib.astensor([0.0])
    for _ in range(10000):
        DummyObject([a])
        test = pyhf.tensorlib.astensor([1]*100000)

main()
```

this still leaks.. maybe something in `events`  keeps track of `self`?

**Comment by matthewfeickert** [comment] 2020-08-19 06:55
@Ga0l Now that PR #1035 is in I think this should be fixed. Can you please try with either `pyhf` installed from `master` through Git or by installing the [dev-release from TestPyPI](https://scikit-hep.org/pyhf/development.html#testpypi)?

**Comment by Ga0l** [comment] 2020-08-19 07:27
I'm testing right now on a big run and memory usage didn't increase after several minutes so it seems to be fixed. Thanks a lot!

**Comment by matthewfeickert** [comment] 2020-08-19 07:33
> I'm testing right now on a big run and memory usage didn't increase after several minutes so it seems to be fixed. Thanks a lot!

Great! Thank you so much for bringing this to our attention. Also nice work @kratsg on the quick fix. :sunglasses:
