### ISSUE TITLE
multichannel-coupled-histo notebook giving NAN with v0.6.0 API

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#1313] opened 2021-02-15 18:05 UTC
# Description

The notebook `multichannel-coupled-histo.ipynb` on the branch `fix/api-for-multichannel-coupled-histo` produces `nan` in the final cell of the notebook. This was found in PR #1312, and should be fixed up.

**Comment by alexander-held** [comment] 2021-02-16 10:47
This seems to be caused by convergence issues, which in turn happen because data lies very far away from the model. There are insufficient degrees of freedom in the model to fit data well.

```
╒════════════╤═══════════════╤════════════════╤════════════════╤════════════════╕
│ sample     │ control       │                │ signal         │                │
│            │ bin 1         │ bin 2          │ bin 1          │ bin 2          │
╞════════════╪═══════════════╪════════════════╪════════════════╪════════════════╡
│ background │ 105.00        │ 100.00         │ 0.00           │ 0.00           │
├────────────┼───────────────┼────────────────┼────────────────┼────────────────┤
│ bkg1       │ 0.00          │ 0.00           │ 100.00         │ 100.00         │
├────────────┼───────────────┼────────────────┼────────────────┼────────────────┤
│ bkg2       │ 0.00          │ 0.00           │ 50.00          │ 120.00         │
├────────────┼───────────────┼────────────────┼────────────────┼────────────────┤
│ signal     │ 0.00          │ 0.00           │ 30.00          │ 35.00          │
├────────────┼───────────────┼────────────────┼────────────────┼────────────────┤
│ total      │ 105.00 ± 7.50 │ 100.00 ± 12.50 │ 180.00 ± 15.00 │ 255.00 ± 15.00 │
├────────────┼───────────────┼────────────────┼────────────────┼────────────────┤
│ data       │ 170.00        │ 220.00         │ 110.00         │ 105.00         │
╘════════════╧═══════════════╧════════════════╧════════════════╧════════════════╛
```
In the control region, data is significantly above the nominal model prediction. The only nuisance parameter that can bring the model closer to data is the `coupled_histosys`. In the signal region, data is significantly below the model prediction (even with no signal present). Pulling the `coupled_histosys` nuisance parameter to positive values improves modeling in the control region, but pulling it to negative values improves it in the signal region. This results in an extreme constraint for this nuisance parameter, and very poor post-fit modeling. With the signal normalization held fixed in the observed limit calculation, the fit fails (apparently silently with `scipy`, and more loudly with `iminuit`).

To get more reasonable results, different data can be used:
```
data = [105, 100, 152, 221] + model.config.auxdata
```
works fine for me locally.

Another set of data:
```
data = [175, 110, 160, 230] + model.config.auxdata
```
works without throwing errors, and I think the sharp features appear because of the lack of degrees of freedom:
![CLs](https://user-images.githubusercontent.com/45009355/108052388-5b81f100-704c-11eb-9885-4e24b358859c.png)
I believe they appear because the best-fit configurations can change drastically at some POI values.

**Comment by kratsg** [comment] 2022-08-30 18:38
@matthewfeickert is this still an issue?

**Comment by alexander-held** [comment] 2022-08-30 20:43
It is, and while having another look I found what is most likely the bug that caused all this: there is a channel loop
```python
for c in pdf.spec["channels"]:
    data += sourcedata[c["name"]]["bindata"]["data"]
```
to build the data, but this is using the wrong order to fill the data. It should instead loop over `pdf.config.channels`:
```python
for c in pdf.config.channels:
    data += sourcedata[c]["bindata"]["data"]
```
As you can see from the yields above, flipping the data yields between control and signal region results in more sensible values. This brings the model closer to data and the fits succeed in that case.

**Closed** 2022-09-09 01:30 UTC
Labels: bug, good first issue, docs
