### ISSUE TITLE
Large cls value difference between v0.6.3 and master

### ISSUE THREAD

**Issue by mdhank** [scikit-hep/pyhf#1720] opened 2021-12-03 17:38 UTC
### Summary

When I try to run

```console
$ pyhf cls --test-poi 0.16 signal.json
```
(file provided to developers) with pyhf, the result depends on the version. For versions before https://github.com/scikit-hep/pyhf/pull/1639, the CLS_exp is about 50% lower than for versions on or after that commit. Testing revealed that this is likely due to the handling of staterrors, as pruning these removed the discrepancy.

### OS / Environment

```console
cat /etc/os-release
NAME="Scientific Linux"
VERSION="7.9 (Nitrogen)"
ID="scientific"
ID_LIKE="rhel centos fedora"
VERSION_ID="7.9"
PRETTY_NAME="Scientific Linux 7.9 (Nitrogen)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:scientificlinux:scientificlinux:7.9:GA"
HOME_URL="http://www.scientificlinux.org//"
BUG_REPORT_URL="mailto:scientific-linux-devel@listserv.fnal.gov"

REDHAT_BUGZILLA_PRODUCT="Scientific Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
REDHAT_SUPPORT_PRODUCT="Scientific Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.9"
```

### Steps to Reproduce

```console (paste below)
pip install --ignore-installed -U "git+https://github.com/scikit-hep/pyhf.git@9fbbbf9740175fcdfe73fedc4351953be18d2664"
pyhf cls --test-poi 0.16 signal.json
```

differs from

```console
pip install --ignore-installed -U "git+https://github.com/scikit-hep/pyhf.git@5ea4e0a7751aa446c286b9697e01a9439622ebb5
pyhf cls --test-poi 0.16 signal.json
```

### File Upload (optional)

pyhf devs sent internal file.

### Expected Results

I expect the behavior to only change slightly between pyhf versions.

### Actual Results

```console
The behavior changes up to 50%.
```

### pyhf Version

```console
pyhf, version 0.6.4.dev33
pyhf, version 0.6.4.dev34
```

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by matthewfeickert** [comment] 2021-12-03 18:13
For this we're comparing to `v0.6.3` and the current [state of `master`](https://github.com/scikit-hep/pyhf/tree/b798ef23c77db6b1d6d606f4b360a5f47fd63dd2).

@kratsg has been able to identify the issue with with `staterror` as pruning modifier types of `staterror` from the workspace in question removes the difference:

* commit a8d34462:
```console
$ pyhf prune -t staterror ws.json | pyhf cls --test-poi 0.16 --backend torch
{
    "CLs_exp": [
        0.0011805804778050168,
        0.0074845548029529455,
        0.04146623165427494,
        0.17762055416827052,
        0.4957891760138955
    ],
    "CLs_obs": 0.5105860394966024
}
```

* [`master`](https://github.com/scikit-hep/pyhf/tree/b798ef23c77db6b1d6d606f4b360a5f47fd63dd2):
```console
$ pyhf prune -t staterror ws.json | pyhf cls --test-poi 0.16 --backend torch
{
    "CLs_exp": [
        0.0011805782059676592,
        0.007484543587818926,
        0.04146618658379227,
        0.17762042937331468,
        0.49578899186050396
    ],
    "CLs_obs": 0.5105860277468133
}
```

and @lukasheinrich has been able to isolate the problem to these lines

https://github.com/scikit-hep/pyhf/blob/b798ef23c77db6b1d6d606f4b360a5f47fd63dd2/src/pyhf/modifiers/staterror.py#L116-L117

added in PR #1639. We'll work on resolving this soon.

**Comment by mdhank** [comment] 2021-12-03 18:25
Is it know which behavior is correct? If the old is known to be fine, I can just run with that version.

**Comment by matthewfeickert** [comment] 2021-12-05 00:47
> Is it know which behavior is correct? If the old is known to be fine, I can just run with that version.

I can't say with certainty yet until we finish diagnosing thing, but if I had to guess the `v0.6.3` behavior is correct.

**Comment by lukasheinrich** [comment] 2021-12-05 13:20
Hi @mdhank  - the prior behavoir is correct and we know where the bug is, just requires implementing a fix. I'll update here once we have one

**Comment by kratsg** [comment] 2022-03-04 17:48
> Hi @mdhank - the prior behavoir is correct and we know where the bug is, just requires implementing a fix. I'll update here once we have one

The issue is understood to be localized around this line: https://github.com/scikit-hep/pyhf/blob/b798ef23c77db6b1d6d606f4b360a5f47fd63dd2/src/pyhf/modifiers/staterror.py#L116-L117

**Closed** 2022-08-28 20:12 UTC
Labels: bug
