### ISSUE TITLE
Iteration limit reached when using histosys modifier.

### ISSUE THREAD

**Issue by FlorentinJ** [scikit-hep/pyhf#1722] opened 2021-12-06 15:37 UTC
### Summary

Hello everyone,

First of all let me thank you for the wonderful package. As a PhD student playing with LHC data for the first time, it is really helpful.

I would like to take into account a systematic uncertainty in my signal, to do that I tried to add the `histosys` modifier to my signal in addition to the `normfactor` for signal strength and the `uncorr_bkguncrt` for my background.

For some reason this caused `pyhf.infer.hypotest` to be stuck in a loop and raise an iteration limit exception (it also prints a lot of "nan" in the error report for the function to minimize, its jacobian and minimum).

I tried replacing `histosys` by `shapesys` and it seems to work normally.

Am I doing something wrong ? Is this a bug?
Can you suggest a workaround for what I am trying to do?

Many thanks

### OS / Environment

```console
Ubuntu 20.04
```

### Steps to Reproduce

```
mod = {
        "channels": [
            { "name": "singlechannel",
              "samples": [
                { "name": "signal",
                  "data": list(signal),
                  "modifiers": [{ "name": "mu", "type": "normfactor", "data": None},
                                { "name": "mod_name", "type": "histosys", "data": {"hi_data": list(hi), "lo_data": list(lo)} }]

                },
                { "name": "background",
                  "data": list(backgr),
                  "modifiers": [ {"name": "uncorr_bkguncrt", "type": "shapesys", "data": list(b_err)} ]
                }
              ]
            }
        ],
        "observations": [
            { "name": "singlechannel", "data": list(obs) }
        ],
        "measurements": [
            { "name": "Measurement", "config": {"poi": "mu", "parameters": [{"bounds": [[0, 1e+6]],"inits": [1.0], "name": "mu"}]} }
        ],
        "version": "1.0.0"
        }
```

### Expected Results

A p-value.

### Actual Results

```console
fun: nan
     jac: array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])
 message: 'Iteration limit reached'
    nfev: 2999989
     nit: 100000
    njev: 100000
  status: 9
 success: False
       x: array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])
Traceback (most recent call last):
   File "/mnt/c/pyhf/optimize/mixins.py", line 49
      assert result.success
AssertionError
```

### pyhf Version

```console
0.62
```

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by matthewfeickert** [comment] 2021-12-06 17:50
@FlorentinJ To be able to give more advice or try to diagnose what is going on we'll need more information. Are you able to share the JSON workspace? If you're not able to do so publicly, can you make a private Gist and send it to the core devs? If you're not able to share it at all, can you create a minimal reproducible example and share that?

It would be additionally useful to have the actual code that you're running (so we can see the backend and optimizer choices among other things).

**Comment by FlorentinJ** [comment] 2021-12-07 09:40
Here is a minimum working example.

```
import pyhf
import numpy as np

# create signal, signal signal errors, background, background error, and data
signal = [118.9594248, 775.1549616, 557.3824662, 328.0977684, 262.8619548,
       159.2521332, 100.731771 ,  68.1138642,  52.764261 ,  31.6585566,
        25.9024554,  17.2683036,  18.2276538,  19.187004 ,  11.5122024,
        12.4715526]

signal_syst_hi = list(0.1*np.array(signal)*np.linspace(0.1, 1, len(signal)))
signal_syst_lo = list(0.7*np.array(signal)*np.linspace(0.1, 1, len(signal)))

data = [2.93924166e+03, 1.04712855e+04, 3.05285293e+03, 9.78561748e+02,
       4.01355678e+02, 1.87982598e+02, 9.49832573e+01, 5.37759678e+01,
       2.12353207e+01, 1.27264092e+01, 9.94596803e+00, 3.92751314e+00,
       9.83877834e-01, 6.84836766e+00, 0, 9.85549002e-01]

background = [2.93924166e+03, 1.02745949e+04, 2.99550872e+03, 1.01638635e+03,
       4.01355678e+02, 1.84451569e+02, 9.49832573e+01, 4.79928422e+01,
       2.66613633e+01, 1.50946668e+01, 8.22799687e+00, 4.93107010e+00,
       3.18808148e+00, 3.95151412e+00, 1.5, 1.23737618e+00]

background_err = [1.44189213e+02, 5.42808785e+02, 1.80860904e+02, 6.90375633e+01,
       2.87764449e+01, 1.46169168e+01, 7.88540249e+00, 4.16541650e+00,
       3.32009430e+00, 2.56324530e+00, 1.64559937e+00, 1.11646870e+00,
       7.69951752e-01, 1.05870756e+00, 0.4, 3.96894247e-01]

# JSON model
mod = {
    "channels": [
        { "name": "singlechannel",
          "samples": [
            { "name": "signal",
              "data": signal,
              "modifiers": [{ "name": "mu", "type": "normfactor", "data": None},
                            { "name": "mod_name", "type": "histosys", "data": {"hi_data": signal_syst_hi, "lo_data": signal_syst_lo} }]
             
            },
            { "name": "background",
              "data": background,
              "modifiers": [ {"name": "uncorr_bkguncrt", "type": "shapesys", "data": background_err} ]
            }
          ]
        }
    ],
    "observations": [
        { "name": "singlechannel", "data": data }
    ],
    "measurements": [
        { "name": "Measurement", "config": {"poi": "mu", "parameters": [{"bounds": [[0, 1e+6]],"inits": [1.0], "name": "mu"}]} }
    ],
    "version": "1.0.0"
    }

ws = pyhf.Workspace(mod)
wsdata = ws.data(ws.model())

# this line takes a long time then fail
pyhf.infer.hypotest(1, wsdata, ws.model(), calctype='asymptotics', return_expected=True, test_stat='qtilde')
```

**Comment by matthewfeickert** [comment] 2021-12-07 16:13
@FlorentinJ I'm unable to reproduce you example on `pyhf` `v0.6.3` and `v0.6.2`

```console
$ docker run --rm -ti python:3.9 /bin/bash
root@32018a2fbd83:/# python -m venv venv && . venv/bin/activate
(venv) root@32018a2fbd83:/# python -m pip install --upgrade pip setuptools wheel
(venv) root@32018a2fbd83:/# python -m pip install 'pyhf==0.6.3'
(venv) root@32018a2fbd83:/# tail -n 5 issue_1722.py  # copying the example in Issue #1722

# this line takes a long time then fail
cls_obs, cls_expected = pyhf.infer.hypotest(1, wsdata, ws.model(), calctype='asymptotics', return_expected=True, test_stat='qtilde')
print(f"CL_s observed: {cls_obs}")
print(f"CL_s expected: {cls_expected}")
(venv) root@32018a2fbd83:/# python issue_1722.py 
/venv/lib/python3.9/site-packages/pyhf/tensor/numpy_backend.py:352: RuntimeWarning: invalid value encountered in log
  return n * np.log(lam) - lam - gammaln(n + 1.0)
CL_s observed: 0.26319911317665245
CL_s expected: 0.2012008685590555
(venv) root@32018a2fbd83:/# python -m pip list
Package     Version
----------- -------
attrs       21.2.0
click       8.0.3
jsonpatch   1.32
jsonpointer 2.2
jsonschema  4.2.1
numpy       1.21.4
pip         21.3.1
pyhf        0.6.3
pyrsistent  0.18.0
PyYAML      6.0
scipy       1.7.3
setuptools  59.5.0
tqdm        4.62.3
wheel       0.37.0
(venv) root@32018a2fbd83:/# python -m pip install 'pyhf==0.6.2'
(venv) root@32018a2fbd83:/# python issue_1722.py 
/venv/lib/python3.9/site-packages/pyhf/tensor/numpy_backend.py:352: RuntimeWarning: invalid value encountered in log
  return n * np.log(lam) - lam - gammaln(n + 1.0)
CL_s observed: 0.26319911317665245
CL_s expected: 0.2012008685590555
```

If I had to take a total guess at what your problem might be, I would think _maybe_ that your version of SciPy is older and has some issues. Please create a new virtual environment and install `pyhf` like I did above and try again.

**Comment by matthewfeickert** [comment] 2021-12-07 16:14
(I'm going to close this as there isn't a reproducible problem, but @FlorentinJ should feel free to continue to post here with questions.)

**Closed by matthewfeickert** 2021-12-07 16:14 UTC
Labels: bug, needs-info

**Comment by FlorentinJ** [comment] 2021-12-07 18:37
Thank you so much! That wes exactly it. A simple `pip install scipy --upgrade` later (from version 1.5.4), and it now works fine.

**Comment by matthewfeickert** [comment] 2021-12-07 19:02
> Thank you so much! That wes exactly it. A simple `pip install scipy --upgrade` later (from version 1.5.4), and it now works fine.

Glad to hear it! :slightly_smiling_face: The reason I suspected `scipy` was because the error was coming from the minimizer failing to converge, and there isn't much in terms of `pyhf` code there.

Out of interest, do you know what version of `scipy` you had where things were failing?
