### ISSUE TITLE
Parameter range/initial value bug (?) or missing documentation in pyhf.infer.hypotest

### ISSUE THREAD

**Issue by kpachal** [scikit-hep/pyhf#1950] opened 2022-08-16 21:20 UTC
### Summary

Hi folks!

When I try to change both the range and initial parameter values from their defaults in a simple model, the parameter initial value resets to zero if its value is inside the range. If the value is outside the range it is not reset (but can't run due to being outside the range anyway).

### OS / Environment

```console
macOS Monterey 12.5
```

### Steps to Reproduce

```python (paste below)
import pyhf
import numpy as np

model = pyhf.simplemodels.uncorrelated_background(
    signal=[1.0], bkg=[10000], bkg_uncertainty = [100]
)
data = [100000] + model.config.auxdata

poi_vals = np.linspace(50, 500, 41)

use_bounds = model.config.suggested_bounds()
use_bounds[model.config.poi_index] = (poi_vals[0]-1,poi_vals[-1]+1)

use_init=model.config.suggested_init()

# V1: not getting set correctly
use_init[model.config.poi_index] = 100.0

results_highstat = [
    pyhf.infer.hypotest(
        test_poi, data, model, test_stat="qtilde", return_expected_set=True, 
        par_bounds=use_bounds, init_pars = use_init
    )
    for test_poi in poi_vals
]

# V2: note that if you comment out the above and run this,
# the parameter gets set correctly (but to a useless value)
use_init[model.config.poi_index] = 40.0

results_highstat = [
    pyhf.infer.hypotest(
        test_poi, data, model, test_stat="qtilde", return_expected_set=True, 
        par_bounds=use_bounds, init_pars = use_init
    )
    for test_poi in poi_vals
]
```

### Expected Results

I expected the parameter value to be initialised at 100 because I told it to do that.

### Actual Results

* Results from running the pseudocode above

```pytb
ValueError: fit initialization parameter (index: 0, value: 0.0) lies outside of its bounds: (49.0, 501.0)
To correct this adjust the initialization parameter values in the model spec or those given
as arguments to pyhf.infer.fit. If this value is intended, adjust the range of the parameter
bounds.
```

* Results when commenting out V1 and setting the initialised parameter to a non-default value, but one outside the bounds

```pytb
ValueError: fit initialization parameter (index: 0, value: 40.0) lies outside of its bounds: (49.0, 501.0)
To correct this adjust the initialization parameter values in the model spec or those given
as arguments to pyhf.infer.fit. If this value is intended, adjust the range of the parameter
bounds.
```

### pyhf Version

```console
pyhf, version 0.6.3
```

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by matthewfeickert** [comment] 2022-08-16 21:54
Hi @kpachal. :wave: I haven't read through this (will try to get to it tonight) but just seeing that in your example you have the POI range be far outside `[0, 10]`

```python
poi_vals = np.linspace(50, 500, 41)
```

you'll probably want to read through parts of Issue #762, specifically https://github.com/scikit-hep/pyhf/issues/762#issuecomment-582060534, to see why we don't recommend this. I think that this is unrelated to your actual question, but I wanted to bring it up before I forgot.

**Comment by kratsg** [comment] 2022-08-16 23:09
> I expected the parameter value to be initialised at 100 because I told it to do that.

Looking at this, I'm not exactly sure what you're intending to do. Remember that a hypotest is going to evaluate at the POI you pass in, not the initial value you want to use (and it isn't fixed by default unless you explicitly state it's a fixed/constant parameter). Try a simpler example here:

```python
import pyhf
import numpy as np
model = pyhf.simplemodels.uncorrelated_background(
    signal=[1.0], bkg=[10000], bkg_uncertainty = [100]
)
data = [100000] + model.config.auxdata
use_bounds = model.config.suggested_bounds()
use_init = model.config.suggested_init()
use_bounds[model.config.poi_index] = (50, 500)
use_init[model.config.poi_index] = 100.0
pyhf.infer.mle.fit(data, model) # array([10.        ,  5.49908988])
pyhf.infer.mle.fit(data, model, init_pars=use_init, par_bounds=use_bounds) # array([500.        ,   5.45458474])
```

As you can see, the parameter changes when doing a regular fit. For hypothesis testing, you're evaluating the POI at different values and computing the test statistic.

**Comment by matthewfeickert** [comment] 2022-08-16 23:56
> For hypothesis testing, you're evaluating the POI at different values and computing the test statistic.

@kpachal Following up on @kratsg's point, as

https://github.com/scikit-hep/pyhf/blob/248e40072ca933813214ada3fd79b10633ffef1d/src/pyhf/infer/mle.py#L56-L64

is evaluated for _every call_ of `pyhf.infer.mle.fit` then if the fit is going poorly because of large swings in parameter values it is very possible that the fit values are going to escape their bounds. In your particular version, if I put in a `breakpoint` into the `pyhf.infer.mle.fit` source code just above

https://github.com/scikit-hep/pyhf/blob/248e40072ca933813214ada3fd79b10633ffef1d/src/pyhf/infer/mle.py#L121-L122

then you can see that the fit is just failing as it is trying to take large steps in the parameter space as the model is asking it to fit wildly incompatible model parameters to observations.

I do exactly that in the following example (click to see the full steps reproduced) and you can see as I step through the fit iterations with `pdb` that the fit struggles and crashes outside of the parameter bounds.

<details>
<summary>Reproducible example in a python:3.10 Docker container:</summary>

This uses the following example

```python
# issue-i950.py
import pyhf
import numpy as np

model = pyhf.simplemodels.uncorrelated_background(
    signal=[1.0], bkg=[10_000], bkg_uncertainty=[100]
)
data = [100_000] + model.config.auxdata

poi_vals = np.linspace(50, 500, 41)

use_bounds = model.config.suggested_bounds()
use_bounds[model.config.poi_index] = (poi_vals[0] - 1, poi_vals[-1] + 1)

use_init = model.config.suggested_init()
use_init[model.config.poi_index] = 100.0

for test_poi in poi_vals:
    print(f"test POI: {test_poi}\n")
    pyhf.infer.hypotest(
        test_poi,
        data,
        model,
        test_stat="qtilde",
        return_expected_set=True,
        par_bounds=use_bounds,
        init_pars=use_init,
    )
```

```console
> docker run --rm -ti python:3.10 /bin/bash
root@6ec362671390:/# python -m venv venv && . venv/bin/activate
(venv) root@6ec362671390:/# python -m pip --quiet install --upgrade pip
(venv) root@6ec362671390:/# python -m pip --quiet install 'pyhf==0.6.3'
(venv) root@6ec362671390:/# apt update && apt install -y vim
(venv) root@6ec362671390:/# vi /venv/lib/python3.10/site-packages/pyhf/infer/mle.py  # inject breakpoint()
(venv) root@6ec362671390:/# vi issue-1950.py
(venv) root@6ec362671390:/# cat issue-1950.py 
import pyhf
import numpy as np

model = pyhf.simplemodels.uncorrelated_background(
    signal=[1.0], bkg=[10_000], bkg_uncertainty=[100]
)
data = [100_000] + model.config.auxdata

poi_vals = np.linspace(50, 500, 41)

use_bounds = model.config.suggested_bounds()
use_bounds[model.config.poi_index] = (poi_vals[0] - 1, poi_vals[-1] + 1)

use_init = model.config.suggested_init()
use_init[model.config.poi_index] = 100.0

for test_poi in poi_vals:
    print(f"test POI: {test_poi}\n")
    pyhf.infer.hypotest(
        test_poi,
        data,
        model,
        test_stat="qtilde",
        return_expected_set=True,
        par_bounds=use_bounds,
        init_pars=use_init,
    )
(venv) root@6ec362671390:/# python issue-1950.py 
test POI: 50.0

qmu_tilde test statistic used for fit configuration with POI not bounded at zero.
Use the qmu test statistic (pyhf.infer.test_statistics.qmu) instead.
> /venv/lib/python3.10/site-packages/pyhf/infer/mle.py(123)fit()
-> _validate_fit_inputs(init_pars, par_bounds, fixed_params)
(Pdb) dir()
['_', 'data', 'fixed_params', 'init_pars', 'kwargs', 'opt', 'par_bounds', 'pdf']
(Pdb) init_pars
[50.0, 1.0]
(Pdb) par_bounds
[(49.0, 501.0), (1e-10, 10.0)]
(Pdb) c
> /venv/lib/python3.10/site-packages/pyhf/infer/mle.py(123)fit()
-> _validate_fit_inputs(init_pars, par_bounds, fixed_params)
(Pdb) init_pars
[100.0, 1.0]
(Pdb) c
> /venv/lib/python3.10/site-packages/pyhf/infer/mle.py(123)fit()
-> _validate_fit_inputs(init_pars, par_bounds, fixed_params)
(Pdb) init_pars
[0.0, 1.0]
(Pdb) c
Traceback (most recent call last):
  File "//issue-1950.py", line 19, in <module>
    pyhf.infer.hypotest(
  File "/venv/lib/python3.10/site-packages/pyhf/infer/__init__.py", line 159, in hypotest
    teststat = calc.teststatistic(poi_test)
  File "/venv/lib/python3.10/site-packages/pyhf/infer/calculators.py", line 340, in teststatistic
    asimov_data = generate_asimov_data(
  File "/venv/lib/python3.10/site-packages/pyhf/infer/calculators.py", line 64, in generate_asimov_data
    bestfit_nuisance_asimov = fixed_poi_fit(
  File "/venv/lib/python3.10/site-packages/pyhf/infer/mle.py", line 203, in fixed_poi_fit
    return fit(data, pdf, init_pars, par_bounds, fixed_params, **kwargs)
  File "/venv/lib/python3.10/site-packages/pyhf/infer/mle.py", line 123, in fit
    _validate_fit_inputs(init_pars, par_bounds, fixed_params)
  File "/venv/lib/python3.10/site-packages/pyhf/infer/mle.py", line 59, in _validate_fit_inputs
    raise ValueError(
ValueError: fit initialization parameter (index: 0, value: 0.0) lies outside of its bounds: (49.0, 501.0)
To correct this adjust the initialization parameter values in the model spec or those given
as arguments to pyhf.infer.fit. If this value is intended, adjust the range of the parameter
bounds.
(venv) root@6ec362671390:/# 
```

</details>


While the example model and the given observations are not ones that I would suggest given their incompatibility, if you scale the model so that you have more reasonable parameter steps then you can get convergence even with this. So let's try the same example that you gave but with things scaled as here

```python
# issue-1950_scaled.py
import pyhf
import numpy as np

model = pyhf.simplemodels.uncorrelated_background(
    signal=[50.0], bkg=[10_000], bkg_uncertainty=[100]
)
data = [100_000] + model.config.auxdata

poi_vals = np.linspace(1.0, 10.0, 41)

use_bounds = model.config.suggested_bounds()
use_bounds[model.config.poi_index] = (poi_vals[0] - 1, poi_vals[-1] + 1)

use_init = model.config.suggested_init()
use_init[model.config.poi_index] = 2.0

for test_poi in poi_vals:
    print(f"test POI: {test_poi}\n")
    pyhf.infer.hypotest(
        test_poi,
        data,
        model,
        test_stat="qtilde",
        return_expected_set=True,
        par_bounds=use_bounds,
        init_pars=use_init,
    )
```

As we see below, as the parameter values steps are more constrained then the fit converges and runs fine.

<details>
<summary>...continuing from above example:</summary>

```console
(venv) root@6ec362671390:/# vi issue-1950_scaled.py
(venv) root@6ec362671390:/# python issue-1950_scaled.py 
test POI: 1.0

> /venv/lib/python3.10/site-packages/pyhf/infer/mle.py(123)fit()
-> _validate_fit_inputs(init_pars, par_bounds, fixed_params)
(Pdb) dir()
['_', 'data', 'fixed_params', 'init_pars', 'kwargs', 'opt', 'par_bounds', 'pdf']
(Pdb) init_pars
[1.0, 1.0]
(Pdb) par_bounds
[(0.0, 11.0), (1e-10, 10.0)]
(Pdb) c
> /venv/lib/python3.10/site-packages/pyhf/infer/mle.py(123)fit()
-> _validate_fit_inputs(init_pars, par_bounds, fixed_params)
(Pdb) init_pars
[2.0, 1.0]
(Pdb) c
> /venv/lib/python3.10/site-packages/pyhf/infer/mle.py(123)fit()
-> _validate_fit_inputs(init_pars, par_bounds, fixed_params)
(Pdb) init_pars
[0.0, 1.0]
(Pdb) c
> /venv/lib/python3.10/site-packages/pyhf/infer/mle.py(123)fit()
-> _validate_fit_inputs(init_pars, par_bounds, fixed_params)
(Pdb) init_pars
[1.0, 1.0]
(Pdb) c
> /venv/lib/python3.10/site-packages/pyhf/infer/mle.py(123)fit()
-> _validate_fit_inputs(init_pars, par_bounds, fixed_params)
(Pdb) init_pars
[2.0, 1.0]
(Pdb) c
test POI: 1.225

> /venv/lib/python3.10/site-packages/pyhf/infer/mle.py(123)fit()
-> _validate_fit_inputs(init_pars, par_bounds, fixed_params)
(Pdb) --KeyboardInterrupt--  # Let's Ctrl+C/Ctrl+D out at this point as we've made the point
...
bdb.BdbQuit
(venv) root@6ec362671390:/# vi /venv/lib/python3.10/site-packages/pyhf/infer/mle.py  # Remove the breakpoint
(venv) root@6ec362671390:/# python issue-1950_scaled.py 
test POI: 1.0

test POI: 1.225

...

test POI: 9.775

test POI: 10.0

(venv) root@6ec362671390:/# 
```

</details>

So what you're seeing here is the same sort of thing as https://github.com/scikit-hep/pyhf/issues/762#issuecomment-582060534.

## Going forward

I don't think that there's much that we can do to try to help the fit along, and I would argue that trying to put too many "bumpers" up to help fits that are not going to go well is probably going to be detrimental in the long run. You're obviously not the first person to attempt to try something like this, so perhaps you could try to give us some feedback on how we might better present things like this that are subtleties either in the docs and/or [in the user guide](https://pyhf.github.io/pyhf-tutorial/). Feedback helps, especially when it is coming from users that have fresh eyes when it comes to both the API and the docs!

**Comment by kpachal** [comment] 2022-08-17 17:18
Hi guys,

thanks a lot - seems I got down a weird side road here based on misinterpreting the error messages I was receiving and what my searches turned up. With this explanation of what parameters actually control what, I can see what's going on a lot better. Thanks!

Cheers,
Kate

**Comment by matthewfeickert** [comment] 2022-08-17 18:34
> With this explanation of what parameters actually control what, I can see what's going on a lot better. Thanks!

Sounds good. :+1: I'll close this for now, but if you have have thoughts on how to make some of this information more clear to the user we would love to hear it in a docs Issue!

**Closed by matthewfeickert** 2022-08-17 18:34 UTC
Labels: question, not-a-bug
