### ISSUE TITLE
Pytorch backend changes global state when initialized

### ISSUE THREAD

**Issue by nikoladze** [scikit-hep/pyhf#921] opened 2020-07-06 06:19 UTC
# Description

The pytorch backend changes some global state when initialized

https://github.com/scikit-hep/pyhf/blob/64dbce070156945f6bb524f79ee6e23d26b52f01/src/pyhf/tensor/pytorch_backend.py#L20

This leads to problems when multiple backend objects are created (as in the tests) because `pyhf.set_backend` won't change it again, for example

```pycon
>>> import pyhf
>>> backend64 = pyhf.tensor.pytorch_backend(precision="64b")
>>> backend32 = pyhf.tensor.pytorch_backend(precision="32b") # this sets the global state
>>> pyhf.set_backend(backend64) # float precision stays at 32b
>>> pyhf.tensorlib.astensor([1.]).dtype
torch.float32
```

I introduced this bug with with #906. @kratsg has an idea how to fix it.

# Checklist

- [x] Run `git fetch` to get the most up to date version of `master`
- [x] Searched through existing Issues to confirm this is not a duplicate issue
- [x] Filled out the Description, Expected Behavior, Actual Behavior, and Steps to Reproduce sections above or have edited/removed them in a way that fully describes the issue

**Comment by matthewfeickert** [comment] 2020-07-06 06:55
Hi @nikoladze, thanks for the Issue. I'm unable to reproduce this bug using the [current `HEAD` of `master`](https://github.com/scikit-hep/pyhf/commit/64dbce070156945f6bb524f79ee6e23d26b52f01) in my local machine and in the following Docker image.

```Dockerfile
FROM python:3.8-slim
RUN apt-get update && \
    apt-get install -y -q git
RUN git clone https://github.com/scikit-hep/pyhf.git && \
    cd pyhf && \
    git checkout 64dbce070156945f6bb524f79ee6e23d26b52f01 && \
    python -m pip install --no-cache .[torch]
ENTRYPOINT ["/bin/bash", "-l", "-c"]
CMD ["/bin/bash"]
```

built with

```
$ docker build . -f Dockerfile -t debug-pyhf:latest
```

If I then use the following file in the same directory

```python
# issue_921.py
import pyhf

backend64 = pyhf.tensor.pytorch_backend(precision="64b")
backend32 = pyhf.tensor.pytorch_backend(precision="32b")
print("Setting backend to PyTorch with 64b precision")
pyhf.set_backend(backend64)
print(f"Observed tensor precision: {pyhf.tensorlib.astensor([1.0]).dtype}")
print("\nSetting backend to PyTorch with 32b precision")
pyhf.set_backend(backend32)
print(f"Observed tensor precision: {pyhf.tensorlib.astensor([1.0]).dtype}")
print("\nSetting backend to PyTorch with 64b precision")
pyhf.set_backend(backend64)
print(f"Observed tensor precision: {pyhf.tensorlib.astensor([1.0]).dtype}")
```

I get the following run output

```
$ docker run --rm -v $PWD:$PWD -w $PWD debug-pyhf:latest "python issue_921.py"
Setting backend to PyTorch with 64b precision
Observed tensor precision: torch.float64

Setting backend to PyTorch with 32b precision
Observed tensor precision: torch.float32

Setting backend to PyTorch with 64b precision
Observed tensor precision: torch.float64
```

Can you give us an example in a Docker image that can produce your error?

**Comment by matthewfeickert** [comment] 2020-07-06 07:15
Ah, okay I can reproduce it if I install from PyPI:

```Dockerfile
FROM python:3.8-slim
RUN apt-get update && \
    apt-get install -y -q git
RUN python -m pip install "pyhf[torch]==0.4.4"
ENTRYPOINT ["/bin/bash", "-l", "-c"]
CMD ["/bin/bash"]
```

built with

```
$ docker build . -f Dockerfile -t debug-pyhf:v0.4.4
```

I then get the following run output

```
$ docker run --rm -v $PWD:$PWD -w $PWD debug-pyhf:v0.4.4 "python issue_921.py"
Setting backend to PyTorch with 64b precision
Observed tensor precision: torch.float32

Setting backend to PyTorch with 32b precision
Observed tensor precision: torch.float32

Setting backend to PyTorch with 64b precision
Observed tensor precision: torch.float32
```

So it seems that this was fixed in PR #914 and so will get patched in release `v0.5.0` of `pyhf`.

@nikoladze I'm going to close this as this shouldn't be affecting the development of PR #902, but thank you for reporting this as we now know where this was introduced and where it was fixed! Let us know if you think we should reopen it.

**Comment by nikoladze** [comment] 2020-07-06 07:55
Oh - seems my example only goes wrong because i ran it in a version of pyhf that did not have the `precision` argument that was introduced in #914. Seems the `astensor` function has no problem with this issue, since it explicitely passes the dtype argument and does not rely on the global state. So one function where it goes wrong also in latest version is the `normal_cdf`. The following script, executed in the docker container @matthewfeickert posted above

```python
# issue_921_normal_cdf.py
import pyhf

backend64 = pyhf.tensor.pytorch_backend(precision="64b")
backend32 = pyhf.tensor.pytorch_backend(precision="32b")
print("Setting backend to PyTorch with 64b precision")
pyhf.set_backend(backend64)
print(f"Observed tensor precision: {pyhf.tensorlib.normal_cdf(1).dtype}")
print("\nSetting backend to PyTorch with 32b precision")
pyhf.set_backend(backend32)
print(f"Observed tensor precision: {pyhf.tensorlib.normal_cdf(1).dtype}")
print("\nSetting backend to PyTorch with 64b precision")
pyhf.set_backend(backend64)
print(f"Observed tensor precision: {pyhf.tensorlib.normal_cdf(1).dtype}")
```

produces the following output for me

```
Setting backend to PyTorch with 64b precision
Observed tensor precision: torch.float32

Setting backend to PyTorch with 32b precision
Observed tensor precision: torch.float32

Setting backend to PyTorch with 64b precision
Observed tensor precision: torch.float32
```

This can be fixed by rewriting `normal_cdf` to explicitly set the dtype as i attempted in #902, but i think @kratsg has a better idea.

**Comment by matthewfeickert** [comment] 2020-07-06 08:15
> produces the following output for me

Yup, I can confirm with

```
docker run --rm -v $PWD:$PWD -w $PWD debug-pyhf:latest "python issue_921_normal_cdf.py"
```

Thanks for the minimal failing example, @nikoladze. Reopening this now.

**Closed** 2020-07-07 07:04 UTC
Labels: bug
